name: CI_Pipeline
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: checkoout_code
        uses: actions/checkout@v6.0.2
        with:
          clean:
      - name: install_nodejs
        uses: actions/setup-node@v6.2.0
        with: 
          node-version: 16.0.0
      - name: check-files
        run: |
           echo "#### list files ###"
           pwd
           ls -lah    
           echo "SHA: $GITHUB_SHA"
           echo "REF: $GITHUB_REF"
      - name: NPM_instal
        run: |
            echo "###### NPM Install #####"
            npm install
            echo "### List file ####"
            ls -lah

            echo "### Node Version ###"
            node -v
            
      - name: build_and_test
        run: |
           echo "##### build ###"
           npm run build

           echo "#### test ###"
           npm run test
           echo "### list files ##"
           ls -lah
           
  deploy: 
   runs-on: ubuntu-22.04
   needs: build
   name: deployment
   steps:
      - name: check-files
        run: |
           echo "#### list files ###"
           pwd
           ls -lah    
           echo "SHA: $GITHUB_SHA"
           echo "REF: $GITHUB_REF"
           echo "event_name=$GITHUB_EVENT_NAME"
           echo "ref=$GITHUB_REF"
           echo "ref_name=${{ github.ref_name }}"
           echo "base_ref=${{ github.base_ref }}"
           echo "head_ref=${{ github.head_ref }}"
      - name: deploy
        run: |
            echo "#### deploying ###"

       
 
   
          




        
      
      
